- hosts: Controller
  vars:
   mysql_root_password: admin
  become: yes
  tasks:
  - name: Create Keystone User
    mysql_user:
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: Controller
     name: "keystone"
     host: "{{ item }}"
     state: present
     password: admin
     priv:
      "keystone.*:ALL,GRANT"
    with_items:
     - localhost
     - ""
     - Controller

  - mysql_user:
     name: "glance"
     state: present
     password: admin
     host: "{{ item }}"
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: Controller
     priv:
      "glance.*:ALL,GRANT"
    with_items:
     - localhost
     - ""
     - Controller

  - mysql_user:
     name: "cinder"
     state: present
     password: admin
     host: "{{ item }}"
     login_user: root
     login_password: "{{ mysql_root_password }}"

     login_host: Controller
     priv:
      "cinder.*:ALL,GRANT"
    with_items:
     - localhost
     - ""
     - Controller

  - mysql_user:
     name: "neutron"
     state: present
     password: admin
     host: "{{ item }}"
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: Controller
     priv:
      "neutron.*:ALL,GRANT"
    with_items:
     - localhost
     - ""
     - Controller

  - mysql_user:
     name: "nova"
     state: present
     password: admin
     host: "{{ item }}"
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: Controller
     priv:
      "nova.*:ALL,GRANT/nova_api.*:ALL,GRANT/nova_cell0.*:ALL,GRANT"
    with_items:
     - localhost
     - ""
     - Controller
