- hosts: ALLSERVER
  become: yes
  tasks:
  - name: "update hostnames"
    hostname:
      name: "{{ hostname }}"
  - name: "Update hosts File"
    blockinfile:
     path: /etc/hosts
     block: |
      10.194.100.11 Controller
      10.194.100.12 Storage
      10.194.100.13 Compute
      
