#Update the hosts in all the server
- hosts: ALLSERVER
  become: yes
  tasks:
  - name: "update hostnames"
    hostname:
      name: "{{ hostname }}"
  - name: "Update hosts File"
    blockinfile:
     path: /etc/hosts
     block: |
      10.194.100.11 Controller
      10.194.100.12 Storage
      10.194.100.13 Compute

# Add Openstack packages in all the server
  - name: "Openstack Queens Repo"
    yum:
      name: centos-release-openstack-queens
      state: present
      update_cache: yes
  - name: "upgrade all packages"
    yum: name=* state=present
  - name: "Openstack Client Installation"
    yum:
      name: python-openstackclient
      state: present
      update_cache: yes
  - name: "Openstack Selinux Installation"
    yum:
      name: openstack-selinux
      state: present
      update_cache: yes
      
