# Create new file for MariaDB Servers
# Install & Configure MariaDB Database
- hosts: Controller
  vars:
   mysql_root_password: admin
  become: yes
  tasks:
  - name: "Install MariaDB Packages"
    yum:
      name: '{{ item }}'
      state: present
      update_cache: yes
    with_items:
      - mariadb
      - mariadb-server
      - python2-PyMySQL
      - pexpect

  - name: "Start and Enabled the Service"
    service:
     name: mariadb
     enabled: true
     state: started

  - name: "secure mariadb"
    expect:
      command: mysql_secure_installation
      responses:
        'Enter current password for root': ''
        'Set root password': 'n'
        'Remove anonymous users': 'y'
        'Disallow root login remotely': 'y'
        'Remove test database': 'y'
        'Reload privilege tables now': 'y'

  - name: Set MySQL root Password
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: ''
      name: 'root'
      host: "{{ item }}"
      password: '{{ mysql_root_password }}'
      state: present
      priv: "*.*:ALL,GRANT"
    with_items:
       - Controller
       - 127.0.0.1
       - ::1
       - localhost

  - name: "Create database openstack config file"
    file:
     path: /etc/my.cnf.d/openstack.cnf
     state: touch

  - name: "Update file with configuration of database"
    blockinfile:
     path: /etc/my.cnf.d/openstack.cnf
     block: |
       [mysqld]
       bind-address = Controller

       default-storage-engine = innodb
       innodb_file_per_table = on
       max_connections = 4096
       collation-server = utf8_general_ci
       character-set-server = utf8

  - name: "Start and Enabled the Service"
    service:
     name: mariadb
     state: restarted
