# Message Queue Configurations
- hosts: Controller
  become: yes
  tasks:
  - name: "Install Message queue Packages"
    yum:
      name: rabbitmq-server
      state: present
      update_cache: yes
  - name: "Start and Enabled the Message queue Service"
    service:
     name: rabbitmq-server
     enabled: true
     state: started

  - name: "Add Openstack users"
    command: rabbitmqctl add_user openstack admin

  - name: "Set permission to the user"
    command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
