# Creating new files for Neutron Compute Service
# Neutron Compute Service
- hosts: Compute
  become: yes
  tasks:
   - name: "Installing & Configuring Neutron Service"
     yum:
      name: ['openstack-neutron-linuxbridge', 'ebtables', 'ipset'] 
      state: present
      update_cache: yes
   
   - name: "Configure the server component"
     blockinfile:
       marker: "#Block 1 Neutron"
       path: /etc/neutron/neutron.conf
       regexp: '^[DEFAULT]'
       insertafter: '^\[DEFAULT\]'
       block: |
         transport_url = rabbit://openstack:admin@Controller
         auth_strategy = keystone
       state: present
   - blockinfile:
       marker: "#Block 2 Neutron"
       path: /etc/neutron/neutron.conf
       regexp: '^[keystone_authtoken]'
       insertafter: '^\[keystone_authtoken\]'
       block: |
         auth_uri = http://Controller:5000
         auth_url = http://Controller:35357
         memcached_servers = Controller:11211
         auth_type = password
         project_domain_name = default
         user_domain_name = default
         project_name = service
         username = neutron
         password = admin
       state: present
   - blockinfile:
       marker: "#Block 3 Neutron"
       path: /etc/neutron/neutron.conf
       regexp: '^[oslo_concurrency]'
       insertafter: '^\[oslo_concurrency\]'
       block: |
         lock_path = /var/lib/neutron/tmp
       state: present

   - name: "Configure the Linux bridge agent"
     blockinfile:
       marker: "#Block 4 Neutron"
       path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
       regexp: '^[linux_bridge]'
       insertafter: '^\[linux_bridge\]'
       block: |
         physical_interface_mappings = provider:eth0
       state: present
   - blockinfile:
       marker: "#Block 5 Neutron"
       path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
       regexp: '^[vxlan]'
       insertafter: '^\[vxlan\]'
       block: |
         enable_vxlan = true
         local_ip = {{ ansible_default_ipv4.address }}
         l2_population = true
       state: present
   - blockinfile:
       marker: "#Block 6 Neutron"
       path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
       regexp: '^[securitygroup]'
       insertafter: '^\[securitygroup\]'
       block: |
         enable_security_group = true
         firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
       state: present

   - name: "Network Bridge Module Enable"
     shell: 'modprobe br_netfilter' 
   - shell: 'sysctl net.bridge.bridge-nf-call-iptables=1'
   - shell: 'sysctl net.bridge.bridge-nf-call-ip6tables=1'

   - name: "Configure the Compute service to use the Networking service"
     blockinfile:
       marker: "#Block 7 Neutron"
       path: /etc/nova/nova.conf
       regexp: '^[neutron]'
       insertafter: '^\[neutron\]'
       block: |
         url = http://Controller:9696
         auth_url = http://Controller:35357
         auth_type = password
         project_domain_name = default
         user_domain_name = default
         region_name = RegionOne
         project_name = service
         username = neutron
         password = admin
       state: present

   - name: "Restart the nova compute services"
     service:
      name: openstack-nova-compute
      enabled: true
      state: restarted

   - name: "Start & Enable the services"
     service:
      name: neutron-linuxbridge-agent
      enabled: true
      state: started
