# Creating new files for Nova Service
# Nova Service
- hosts: Controller
  become: yes
  tasks:
   - name: "Installing & Configuring Nova Service"
     yum:
      name: ['openstack-nova-api', 'openstack-nova-conductor', 'openstack-nova-console', 'openstack-nova-novncproxy', 'openstack-nova-scheduler', 'openstack-nova-placement-api']
      state: present
      update_cache: yes
   
   - name: "Add Connection String In the Config File"
     blockinfile:
       marker: "#Block 1 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[DEFAULT]'
       insertafter: '^\[DEFAULT\]'
       block: |
         enabled_apis = osapi_compute,metadata
         transport_url = rabbit://openstack:admin@Controller
         my_ip = {{ ansible_default_ipv4.address }}
         use_neutron = True
         firewall_driver = nova.virt.firewall.NoopFirewallDriver
       state: present
   - blockinfile:
       marker: "#Block 2 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[keystone_authtoken]'
       insertafter: '^\[keystone_authtoken\]'
       block: |
         auth_url = http://Controller:5000/v3
         memcached_servers = Controller:11211
         auth_type = password
         project_domain_name = default
         user_domain_name = default
         project_name = service
         username = nova
         password = admin
       state: present
   - blockinfile:
       marker: "#Block 3 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[vnc]'
       insertafter: '^\[vnc\]'
       block: |
        enabled = true
        server_listen = $my_ip
        server_proxyclient_address = $my_ip
       state: present
   - blockinfile:
       marker: "#Block 4 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[placement]'
       insertafter: '^\[placement\]'
       block: |
        os_region_name = RegionOne
        project_domain_name = Default
        project_name = service
        auth_type = password
        user_domain_name = Default
        auth_url = http://Controller:5000/v3
        username = placement
        password = admin
       state: present
   - blockinfile:
       marker: "#Block 5 Nova"
       path: /etc/httpd/conf.d/00-nova-placement-api.conf
       block: |
        <Directory /usr/bin>
          <IfVersion >= 2.4>
             Require all granted
          </IfVersion>
          <IfVersion < 2.4>
             Order allow,deny
             Allow from all
          </IfVersion>
        </Directory>
       state: present
   - blockinfile:
       marker: "#Block 6 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[api_database]'
       insertafter: '^\[api_database\]'
       block: |
         connection = mysql+pymysql://nova:admin@Controller/nova_api
   - blockinfile:
       marker: "#Block 7 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[database]'
       insertafter: '^\[database\]'
       block: |
         connection = mysql+pymysql://nova:admin@Controller/nova
   - blockinfile:
       marker: "#Block 8 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[oslo_concurrency]'
       insertafter: '^\[oslo_concurrency\]'
       block: |
         lock_path = /var/lib/nova/tmp
   - blockinfile:
       marker: "#Block 9 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[glance]'
       insertafter: '^\[glance\]'
       block: |
         api_servers = http://Controller:9292
   - blockinfile:
       marker: "#Block 10 Nova"
       path: /etc/nova/nova.conf
       regexp: '^[api]'
       insertafter: '^\[api\]'
       block: |
         auth_strategy = keystone

   - name: "Restart the httpd services"
     service:
      name: httpd
      enabled: true
      state: restarted

   - name: "initialize nova database"
     shell: su -s /bin/sh -c "nova-manage api_db sync" nova && su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova && su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova && su -s /bin/sh -c "nova-manage db sync" nova
     ignore_errors: true

   - name: "Start & Enable the services"
     service:
      name: "{{ item }}"
      enabled: true
      state: started
     with_items:
      - openstack-nova-api.service
      - openstack-nova-consoleauth.service
      - openstack-nova-scheduler.service
      - openstack-nova-conductor.service
      - openstack-nova-novncproxy.service  
