# Creating new files
# Service Account
- hosts: Controller
  vars:
   service_password: admin
  become: yes
  tasks:
   - name: "Create Service User Account"
     shell: . /root/admin-openrc && openstack user create --domain default --password "{{ service_password }}" glance && openstack role add --project service --user glance admin && openstack service create --name glance --description "OpenStack Image" image
   - shell: . /root/admin-openrc && openstack user create --domain default --password "{{ service_password }}" nova && openstack role add --project service --user nova admin && openstack service create --name nova --description "OpenStack Compute" compute
   - shell: . /root/admin-openrc && openstack user create --domain default --password "{{ service_password }}" placement && openstack role add --project service --user placement admin && openstack service create --name placement --description "Placement API" placement
   - shell: . /root/admin-openrc && openstack user create --domain default --password "{{ service_password }}" neutron && openstack role add --project service --user neutron admin && openstack service create --name neutron --description "OpenStack Networking" network
   - shell: . /root/admin-openrc && openstack user create --domain default --password "{{ service_password }}" cinder && openstack role add --project service --user cinder admin && openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2 && openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3
